# Generated by Django 5.0.1 on 2026-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_compare_at_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_sku_per_store',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_store_i_719494_idx',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('full_slug',)},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('slug',)},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique_product_sku_per_store'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
