# Generated by Django 5.0.1 on 2026-06-04 04:41

import random
import string
from django.db import migrations, models


def generate_order_number():
    chars = string.ascii_uppercase + string.digits
    random_part = ''.join(random.choices(chars, k=6))
    return f"ORD-{random_part}"


def populate_order_numbers(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    used_numbers = set()
    for order in Order.objects.all():
        order_number = generate_order_number()
        while order_number in used_numbers:
            order_number = generate_order_number()
        used_numbers.add(order_number)
        order.order_number = order_number
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, null=True, editable=False),
        ),
        migrations.RunPython(populate_order_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, editable=False),
        ),
    ]
