# Generated by Django 5.0.1 on 2026-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_updated_at_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_store_i_610c63_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_store_i_b17b04_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_store_i_8955ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_store_i_2d8de6_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='orders_orde_custome_ca0107_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['updated_at'], name='orders_orde_updated_94e16c_idx'),
        ),
    ]
