# Generated by Django 5.0.1 on 2026-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(default='home', max_length=50),
        ),
    ]
