# Generated by Django 5.0.1 on 2026-06-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='logo',
        ),
    ]
