# Generated by Django 5.0.1 on 2026-06-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_initial'),
        ('products', '0004_remove_product_unique_product_sku_per_store_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('category', 'name')},
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='store',
        ),
    ]
