# Generated by Django 6.0.2 on 2026-02-13 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(help_text='Which category this attribute belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.category'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='tenants.store'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(help_text='Which attribute this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='attributes.attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('store', 'category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
    ]
