# Generated by Django 5.0.1 on 2026-04-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_order_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_store_i_610c63_idx',
            old_name='orders_order_store_s_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_store_i_b17b04_idx',
            old_name='orders_order_store_c_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_store_i_8955ea_idx',
            old_name='orders_order_store_d_idx',
        ),
    ]
