# Generated by Django 5.0.1 on 2026-06-05 04:33

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_fix_order_numbers'),
        ('tenants', '0002_remove_logo_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.generate_order_number, editable=False, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'updated_at'], name='orders_orde_store_i_2d8de6_idx'),
        ),
    ]
