# Generated by Django 5.0.1 on 2026-04-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_status_changed', 'Order Status Changed'), ('order_return_requested', 'Order Return Requested'), ('product_created', 'Product Created'), ('product_deleted', 'Product Deleted'), ('product_low_stock', 'Product Low Stock'), ('category_created', 'Category Created'), ('category_deleted', 'Category Deleted'), ('attribute_created', 'Attribute Created'), ('attribute_deleted', 'Attribute Deleted'), ('store_created', 'Store Created')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='notificatio_store_i_84d170_idx'), models.Index(fields=['store', 'is_read'], name='notificatio_store_i_cbea03_idx')],
            },
        ),
    ]
