# Generated by Django 5.2.5 on 2026-04-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_status_changed', 'Order Status Changed'), ('order_return_requested', 'Order Return Requested'), ('product_created', 'Product Created'), ('product_deleted', 'Product Deleted'), ('product_low_stock', 'Product Low Stock'), ('category_created', 'Category Created'), ('category_deleted', 'Category Deleted'), ('attribute_created', 'Attribute Created'), ('attribute_deleted', 'Attribute Deleted'), ('store_created', 'Store Created')], max_length=30),
        ),
    ]
