# Generated by Django 5.0.1 on 2026-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_store_i_84d170_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_store_i_cbea03_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='store',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'),
        ),
    ]
