# Generated by Django 5.0.1 on 2026-06-03 09:49

from django.db import migrations, models


def populate_full_slug(apps, schema_editor):
    """Populate full_slug for existing categories based on parent hierarchy."""
    Category = apps.get_model('products', 'Category')

    def get_full_slug(category):
        if category.parent_id:
            parent = Category.objects.get(pk=category.parent_id)
            parent_full_slug = get_full_slug(parent)
            return f"{parent_full_slug}/{category.slug}"
        return category.slug

    # Process categories by level to ensure parents are processed first
    for category in Category.objects.all().order_by('level'):
        category.full_slug = get_full_slug(category)
        category.save(update_fields=['full_slug'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear full_slug."""
    Category = apps.get_model('products', 'Category')
    Category.objects.all().update(full_slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0002_remove_logo_field'),
    ]

    operations = [
        # Step 1: Remove old unique constraint
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        # Step 2: Add full_slug field (without unique constraint yet)
        migrations.AddField(
            model_name='category',
            name='full_slug',
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
        # Step 3: Populate full_slug for existing data
        migrations.RunPython(populate_full_slug, reverse_populate),
        # Step 4: Add unique constraint on (store, full_slug)
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'full_slug')},
        ),
    ]
