# Generated by Django 5.0.1 on 2026-05-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sku_unique_per_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='variantattributevalue',
            name='created_at',
        ),
    ]
