# Generated by Django 5.2.5 on 2026-03-30 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_initial'),
        ('products', '0003_product_description_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='attribute_value',
            field=models.ForeignKey(blank=True, help_text='Link image to a specific attribute value (e.g., Color: Red). Leave empty for general product images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='attributes.attributevalue'),
        ),
    ]
