# Generated by Django 5.2.5 on 2026-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_backfill_product_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='is_thumbnail',
            field=models.BooleanField(default=False, help_text='Mark this image as the product thumbnail. Only one per product.'),
        ),
    ]
