# Generated by Django 5.2.5 on 2026-04-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_is_thumbnail_to_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.PositiveIntegerField(default=0, help_text='Reserved by orders (pending/confirmed/processing)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reserved',
            field=models.PositiveIntegerField(default=0, help_text='Reserved by orders (pending/confirmed/processing)'),
        ),
    ]
